name: rl
channels:
  - defaults
dependencies:
  - python=3.12
  - pip=25.0
  - setuptools=75.8.0
  - wheel=0.45.1
  - numpy=2.2.3
  - pandas=2.2.3
  - matplotlib=3.10.1
  - gymnasium=1.0.0
  - stable-baselines3=2.5.0
  - streamlit=1.44.1
  - pip:
      - absl-py==2.1.0
      - ale-py==0.10.2
      - altair==5.5.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.71.0
      - idna==3.10
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - narwhals==1.34.0
      - networkx==3.3
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pillow==11.0.0
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pydeck==0.9.1
      - pygame==2.6.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - referencing==0.36.2
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.24.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - toml==0.10.2
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchvision==0.21.0+cu126
      - tornado==6.4.2
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - --extra-index-url https://download.pytorch.org/whl/cu126
